version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./client:/app  # Mount local code into the container
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file system watching in certain environments

  server:
    image: cosmtrek/air
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1313:1313
    volumes:
      - ./:/app/
  db:
    image: mysql:5.7.26
    container_name: godockerDB
    environment:
      MYSQL_USER: lab2324omada7
      MYSQL_ROOT_PASSWORD: lab2324omada7
      MYSQL_PASSWORD: lab2324omada7
      MYSQL_DATABASE: lab2324omada7_tainia
    ports:
      - "3307:3306"
